### ISSUE TITLE
我不想喷的真的

### ISSUE THREAD

**Issue by Anehta** [xiecg/vue-picker#10]
但是做的真的是太垃圾了啊。。
安卓直接卡死。
ios滑动的快的一批。
虽然开源精神我很支持，但是能写写好再发出来么。。

**Comment by Anehta** [comment]
还有，webpack压缩的时候就压缩不了你这代码。

**Comment by Anehta** [comment]
干

**Comment by v2018z** [comment]
vue2.0中，<picker-item> v-for 求加 :key.

**Comment by v2018z** [comment]
拜托再处理下惯性问题，顺便写好测试。阿门
