### ISSUE TITLE
关联地址修改数据时 直接死循环

### ISSUE THREAD

**Issue by ArrayBuffer** [xiecg/vue-picker#12]
!!!

**Comment by xiecg** [comment]
@ArrayBuffer 

你好，例子里面有修改数据的例子的。

https://github.com/xiecg/vue-picker/blob/master/example/src/components/City.vue#L63

如果依然出现的话还请提供一个 demo 。

**Comment by ArrayBuffer** [comment]
@xiecg  三级联动时 更改省份 需要更新 城市 和 区域 。
只更改城市 不会死循环  但是同时更改城市和区域时 就会死循环。

      onValuesChange: function (province, city, county) {
        // console.log(province);
        if (this.prov !== province['name']) {
          let citys = province['sub'];
          this.cityItems[1].values = citys;
          this.city = citys[0]['name'];
          this.cityItems[2].values = citys[0]['sub'] || [];
        }`
`

**Comment by xiecg** [comment]
@ArrayBuffer 

change 的时候，
`this.cityItems[1].values = citys;  
this.cityItems[2].values = citys[0]['sub'] || []; `
都会产生一个新的引用，所以会死循环。

建议把数据先处理好，存放在一个数组里，每次 change 时查找对应的数据。
