### ISSUE TITLE
在安卓下不显示界面

### ISSUE THREAD

**Issue by crossgit** [xiecg/vue-picker#2]
我用的vue-cli,加入vue-3d-picker后,在安卓机的浏览器下不显示界面,在苹果机和pc上都可以

**Comment by xiecg** [comment]
@crossgit  需要配置  [postcss](https://github.com/postcss/postcss-loader)

**Comment by crossgit** [comment]
真是这原因吗?我把picker.vue下的样式都删除掉了,我的操作就是,
1  npm install vue-3d-picker,
2 在main.js里引入 
import Picker from 'vue-3d-picker'; 
Vue.component(picker.name, picker);
在其他地方没再做处理.
但是在安卓机里打开vue-cli的默认的界面,还是没有内容.

我也尝试配置postcss,没效果.

**Comment by xiecg** [comment]
@crossgit 

我这边测试用的安卓是可以正常显示的，请用控制台查看picker的css有没有加浏览器的私有前缀，如果有依然无法显示，请告知我你的安卓手机以及安卓的版本。如果允许，整理一份demo发到我的邮件上。感谢。

**Comment by crossgit** [comment]
您好,我这边用的是安卓4.4.2和5.0.2两个版本测试的,
vue-cli 创建的项目好像不能直接引用vue-3d-picker .
能否方便把上面的demo发我邮件学习一下? 非常感谢,我不知道该怎么处理了.

**Comment by crossgit** [comment]
@xiecg 
我的邮箱是 xhken000@163.com,非常感谢

**Comment by imlimiao** [comment]
我现在的问题也是，在安卓上能展示，但是滑动的时候，变成一团了，3D模式失效，怎么解决哇--

**Comment by imlimiao** [comment]
配置好post-CSS 就好了
