### ISSUE TITLE
在ios下在某一列在垂直距离滑动很长距离,回弹之后会显示0,这是为什么呢

### ISSUE THREAD

**Issue by groveLqh** [xiecg/vue-picker#3]

**Comment by xiecg** [comment]
@Liqihan 

截图给我 -_-

**Comment by groveLqh** [comment]
![img_4981](https://cloud.githubusercontent.com/assets/16573314/21248788/6f92b05a-c374-11e6-874c-e38bad532e8b.PNG)
![img_4982](https://cloud.githubusercontent.com/assets/16573314/21248789/6f93bdf6-c374-11e6-943e-5d4c49e388bc.PNG)
逻辑说一遍，页面是用的dpr，viewport 0.5，做省市区三级的，想省变了之后市和区一起跟着变，在你代码759行，修改成了这样this.$emit('change', this.getItemValue(), this.$el, this.reset);到此没有问题，然后修改样式，把picker-content的高调到了432px，滑动就出现了这个问题，目前只在ios上有这个问题

**Comment by groveLqh** [comment]
我在垂直距离滑动很长距离之后,就会出现,是和js有关么?

**Comment by xiecg** [comment]
为什麽picker组件内字体那麽小? 用了rem ?

关于处理省市区的，可以查看例子。

**Comment by groveLqh** [comment]
是的,样式是这么处理的,viewport设置成0.5了,所以整体都变小了一倍

**Comment by xiecg** [comment]
picker 组件使用的单位是px，你需要依赖工具把他转为rem。

**Comment by groveLqh** [comment]
恩,这个我知道,可是问题不是出在这里啊,样式什么的我都好改
